base_configs:
  - config/base.yaml
  - config/paths.yaml
name: swin_v2_base_1e-5_xl_512_256_mamba
fsdp: off
fp16: off
data:
  dataset: inaturalist
  crop_size: 512
  val_crop_size: 512
  batch_size: ${train.batch_size}
  val_batch_size: ${train.val_batch_size}
  num_workers: 1
  num_classes: 284
  interpolation: bilinear
  test_crop: False
  aug:
    auto_augment: rand-m9-mstd0.5-inc1
    color_jitter: 0.4
    reprob: 0.0
    remode: pixel
    recount: 1
    mixup: 0.0
    cutmix: 0.0
    label_smoothing: 0.3
    random_resized_crop: False
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  supercategories:
    - Reptilia
model:
  name: EncoderDecoder
  num_classes: ${data.num_classes}
  mlp_ratio: 4
  backbone_class: swinv2_base_window16_256_timm
  backbone:
    img_size: 256
    input_dim: 3
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_base_patch4_window16_256.pth
  cls_head: xl
  context:
    hidden_size: 768
    classification_mode: off
    attention_method: mamba
    tiling: naive_two_stream
    n_layer: 4
  resume: ""
optimizer:
  name: adamw
  lr5
  lr: 1e-5
  classifier_ratio: 1.0
  warmup_epochs: 0
train:
  epochs: 100
  batch_size: 16
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 1
  test_reset: True
  clip_grad: 5.0
val: False
losses:
  losses:
    - name: cls
      type: CrossEntropy
      params:
        field: label
      weight: 1.0
      display: on
