base_configs: 
  - config/inaturalist_revswin/base_512.yaml
name: revswin_base_512_lr3e-5
data:
  crop_size: 512
model:
  backbone:
    img_size: 512
optimizer:
  name: AdamW
  base_lr: 3e-5
train:
  batch_size: 12