base_configs: 
  - config/base.yaml
  - config/cluster_paths_inat.yaml
  # - config/cluster_paths_em.yaml
name: revswin_ep100_base_256
data:
  dataset: inaturalist
  crop_size: 256
  batch_size: ${train.batch_size}
  val_batch_size: ${train.val_batch_size}
  num_workers: 8
  num_classes: 284
  interpolation: bilinear
  test_crop: True
  aug:
    auto_augment: rand-m9-mstd0.5-inc1
    color_jitter: 0.4
    reprob: 0.0
    remode: pixel
    recount: 1
    mixup: 0.0
    cutmix: 0.0
    label_smoothing: 0.3
    random_resized_crop: False
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  supercategories:
    - Reptilia
model: 
  name: EncoderDecoderV2
  num_classes: ${data.num_classes}
  mlp_ratio: 4
  backbone_class: revswinv2_base_window16_256_xview
  backbone:
    img_size: 256
    input_dim: 3
    use_vanilla_backward: False
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_base_window16_256.pth
    upsample: False
  xl_context:
    enabled: True
    n_layer: 1
  resume: ''
optimizer:
  name: AdamW
  base_lr: 1e-5
  classifier_ratio: 1.0
  warmup_epochs: 2
train:
  epochs: 100
  batch_size: 192
  val_batch_size: ${train.batch_size}
  freeze_epochs: 0
  test_every: 1
  test_reset: True
  clip_grad: 5.0
val: False
losses:
  losses:
    - name: cls
      type: CrossEntropy
      params: 
        field: label 
      weight: 1.0
      display: on
