base_configs: 
  - config/revswin_xl/4096_chip512_lr1e-3.yaml
name: revswinv2_xl_4096_chip512_swinpt_lr1e-4_head3x
optimizer:
  base_lr: 1e-4
  classifier_ratio: 3.0
  warmup_epochs: 0
train:
  epochs: 20
  batch_size: 24