base_configs: 
  - config/revswin_xl/4096_chip512_lr1e-3.yaml
name: revswinv2_xl_4096_chip512_swinpt_lr7e-4_wd1e-2
optimizer:
  base_lr: 7e-4
  classifier_ratio: 1.0
  warmup_epochs: 0
  weight_decay: 1e-2
train:
  epochs: 20
  batch_size: 24