name: TimmUnet
encoder:
  name: revswinv2_tiny_window16_256_xview
  in_chans: 2
  drop_path_rate: 0.2
  pretrained: False
  channel_last: True
  patch_size: 16
  input_size: 256
resume: ''
tiling: 'naive'