repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
    -   id: black
        args: ["-l", "999"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: 
          - --max-line-length=120
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify