name: scalemae
channels: 
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - pytorch==2.0.1
  - torchvision==0.15.2
  - pytorch-cuda=11.8
  - scikit-image
  - rasterio==1.2.10
  - gdal
  - shapely
  - openslide==3.4.1
  - openslide-python==1.3.1