name: scalemae
channels: 
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - geopandas
  - pytorch==1.13.1=py3.9_cuda11.6_cudnn8.3.2_0 
  - torchvision==0.14.1 
  - pytorch-cuda=11.6 
  - scikit-image
  - rasterio==1.2.10
  - gdal
  - shapely