#!/bin/bash

NUM_GPUS=$1
DATA_DIR=$2
SHORE_DIR=$3
VAL_OUT_DIR=$4

./train.sh $NUM_GPUS $DATA_DIR $SHORE_DIR $VAL_OUT_DIR 77 v2l
./train.sh $NUM_GPUS $DATA_DIR $SHORE_DIR $VAL_OUT_DIR 99 v2l
./train.sh $NUM_GPUS $DATA_DIR $SHORE_DIR $VAL_OUT_DIR 99 v2m
./train.sh $NUM_GPUS $DATA_DIR $SHORE_DIR $VAL_OUT_DIR 77 b7
./train.sh $NUM_GPUS $DATA_DIR $SHORE_DIR $VAL_OUT_DIR 77 r34
./train.sh $NUM_GPUS $DATA_DIR $SHORE_DIR $VAL_OUT_DIR 77 nf0