distributed: True
fsdp: False
fp16: True
name: revswinv2_chip512_swinpt_lr1e-3
output_dir: ${oc.env:OUTPUT_DIR, "/shared/jacklishufan/large-image-models/new"} 
test: False
val: False
data:
  dataset: inaturalist
  dir: ${oc.env:INATURALIST_ROOT, "/shared/ritwik/data/inaturalist"} 
  num_workers: 8
  test: False
  crop_size: 2048
  val_crop_size: 2048
  transforms:
    names:
      - Normalize
      - HorizontalFlip
      - RandomCrop
      - AutoAugment
      - ColorJitter
    mean: [0.,0.,0.]
    std: [1.,1.,1.]
    max_size: 2048
    height: 2048
    width: 2048
  transforms_val: 
    names:
      - SmallestMaxSize
      - Normalize
    mean: [0.,0.,0.]
    std: [1.,1.,1.]
    max_size: 2048
    height: 2048
    width: 2048
model: 
  name: EncoderDecoderV2
  patch_size: 16
  backbone_class: revswinv2_tiny_window16_256_xview
  backbone:
    in_chans: 3
    input_dim: 3
    drop_path_rate: 0.1
    pretrained:  ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_tiny_window16_256.pth
    channel_last: True
    use_vanilla_backward: False
    img_size: 512
  resume: ''
  tiling: 'naive'
  xl_context:
    enabled: False
    context_patch_len: 100
    no_memory: false
    tiling: ${model.tiling}
optimizer:
  name: adamw 
  base_lr: 1e-3
  min_lr_ratio: 0.01
  classifier_ratio: 1.0
  warmup_epochs: 0
  weight_decay: 0.05
  scheduler: cosine
  mode: step
train:
  epochs: 20
  batch_size: 32
  val_batch_size: 32
  freeze_epochs: 0
  freeze_bn: false
  test_every: 1
  test_reset: True
  grad_clip: 5.0
  label_smoothing: 0.3
losses:
  losses:
    - name: cls
      type: CrossEntropy
      params: 
        field: label 
      weight: 1.0
      display: on
