base_configs:
  - config/base.yaml
  - config/cluster_paths_inat.yaml
name: revswin_base_inat-rep_cs512_bis512
data:
    dataset: inaturalist
    num_workers: 16
    test: false
    batch_size: ${train.batch_size}
    val_batch_size: ${train.val_batch_size}
    crop_size: 512
    num_classes: 284
    test_crop: false
    interpolation: bilinear
    val_crop_size: 512
    overlap: 10
    positive_ratio: 0.85
    fold: 77
    multiplier: 64
    supercategories:
    - Reptilia
    aug:
      auto_augment: rand-m9-mstd0.5-inc1
      color_jitter: 0.4
      reprob: 0.0
      remode: pixel
      recount: 1
      mixup: 0.0
      cutmix: 0.0
      cutmix_minmax: null
      mixup_prob: 1.0
      mixup_switch_prob: 0.5
      mixup_mode: batch
      label_smoothing: 0.3
      random_resized_crop: false
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
model:
    name: EncoderDecoderV2
    resume: ''
    tiling: naive
    backbone_class: revswinv2_base_window16_256_xview
    patch_size: 16
    num_classes: ${data.num_classes}
    mlp_ratio: 4
    backbone:
      in_chans: 3
      input_dim: 3
      drop_path_rate: 0.2
      pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_base_window16_256.pth
      channel_last: true
      img_size: 512
      use_vanilla_backward: false
      upsample: false
    xl_context:
      enabled: false
      no_memory: false
      n_layer: 12
      tiling: ${model.tiling}
      context_patch_len: 100
optimizer:
    name: sgd
    base_lr: 0.0001
    min_lr_ratio: 0.01
    classifier_ratio: 1.0
    warmup_epochs: 0
    weight_decay: 0.0001
    scheduler: cosine
    mode: step
    momentum: 0.9
    nesterov: true
train:
    epochs: 20
    batch_size: 32
    val_batch_size: 1
    freeze_epochs: 0
    freeze_bn: false
    test_every: 1
    test_reset: true
    clip_grad: 5.0
losses:
    losses:
    - params:
        field: label
      name: cls
      type: CrossEntropy
      weight: 1.0
      display: true
fp16: true
fsdp: false
test: false
val: false
eval_sampler: false