losses:
  - name: msk_v
    type: ComboLossCalculator
    weight: 1.0
    display: True
    params:
      field: vessel_mask
      weights:
        bce: 1
        focal: 3
        dice: 1
  - name: msk_f
    type: ComboLossCalculator
    weight: 2.0
    display: True
    params:
      field: fishing_mask
      weights:
        bce: 1
        focal: 3
        dice: 1
  - name: center
    type: CenterLossCalculator
    weight: 3e-7
    display: True
    params: 
  - name: length
    type: LengthLoss
    weight: 2
    display: True
    params: