base_configs: 
  - config/base.yaml
  # - config/cluster_paths.yaml
name: revswinv2_chip1024_swinpt_lr3e-3_head10x_eval
output_dir: outputs/${name}/
data:
  crop_size: 1024
  val_crop_size: 1024
  num_workers: 8
model: 
  backbone:
    img_size: 1024
    pretrained: False
  xl_context:
    enabled: False
    no_memory: False
    n_layer: 12
  resume: /home/tyler/scale-mae-detection-xview/output/revswinv2/val_only_TimmUnet_revswinv2_tiny_window16_256_xview_77_3ghwtfbj_xview
optimizer:
  base_lr: 3e-3
  classifier_ratio: 1.0
  warmup_epochs: 0
train:
  epochs: 20
  batch_size: 24
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 1
  test_reset: False
test: True
val: False