
base_configs: 
  - config/base.yaml
  # - config/cluster_paths_xview_bair.yaml
  - config/cluster_paths.yaml
name: xview_swin_v2_base_1e-5_xl_512_256
fsdp: False
distributed: true
fp16: False
output_dir: ${oc.env:OUTPUT_DIR, "/shared/jacklishufan/large-image-models/new"} 
test: False 
val: False
data:
  dataset: xview3
  dir: ${oc.env:XVIEW3_ROOT, "/shared/group/xview3"} 
  shoreline_dir: ${oc.env:XVIEW3_ROOT, "/shared/group/xview3"} /shoreline/validation
  folds_csv:  ${oc.env:XVIEW3_FOLD_PATH, "meta/folds.csv"} 
  fold: 77
  multiplier: 1
  num_workers: 8
  test: False
  crop_size: 512
  val_crop_size: ${data.crop_size}
  batch_size: ${train.batch_size}
  val_batch_size: ${train.val_batch_size}
  overlap: 10
  positive_ratio: 0.85
  num_classes: 284
  interpolation: bilinear
  test_crop: False
  aug:
    auto_augment: rand-m9-mstd0.5-inc1
    color_jitter: 0.4
    reprob: 0.0
    remode: pixel
    recount: 1
    mixup: 0.0
    cutmix: 0.0
    label_smoothing: 0.3
    random_resized_crop: False
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
model: 
  name: EncoderDecoderV2
  num_classes: ${data.num_classes}
  mlp_ratio: 4
  backbone_class: swinv2_base_window16_256_timm_xview
  backbone:
    img_size: 256
    input_dim: 3
    use_vanilla_backward: False
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_base_patch4_window16_256.pth
    upsample: False
  xl_context:
    skip_connection: off # on
    enabled: on
    hidden_size: 256
    classification_mode: off
    tiling: naive_two_stream
    grad_ratio: 1.0
    n_layer: 4
    mem_chip: 1
  resume: '' # /shared/jacklishufan/inatualist/checkpoints/EncoderDecoderV2_revswinv2_tiny_window16_256_xview_77_hwcy21mb_accuracy_top1.ckpt
optimizer:
  name: adamw
  base_lr: 1e-5
  classifier_ratio: 1.0
  warmup_epochs: 0
train:
  epochs: 120
  batch_size: 64
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 20
  test_reset: True
  clip_grad: 5.0
losses:
  losses:
    - name: mask_vessel
      type: Combo
      params: 
        field: vessel_mask 
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 1.0 
      display: True
    - name: mask_fishing 
      type: Combo
      params: 
        field: fishing_mask
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 2.0 
      display: True
    - name: center 
      type: Center
      params: 
      weight: 3e-7
      display: True
    - name: length
      type: Length
      params: 
      weight: 2.0
      display: True
eval_sampler: False
