base_configs:
  # - config/base.yaml
  - config/cluster_paths.yaml
distributed: True
fsdp: False
fp16: True
name: xview_swin_base_xl_512_lr1e-3
test: False
val: False
data:
  dataset: xview3
  fold: 77
  multiplier: 64
  num_workers: 8
  test: False
  crop_size: ${model.backbone.img_size}
  val_crop_size: ${model.backbone.img_size}
  batch_size: ${train.batch_size}
  val_batch_size: ${train.val_batch_size}
  overlap: 10 
  positive_ratio: 0.85
  supercategories:
  category_label_path: ''
model: 
  name: EncoderDecoderV2
  patch_size: 16
  mlp_ratio: 4
  # backbone_class: swinv2_large_window16_256_timm
  # backbone_class: get_hiera_model_base
  # backbone_class: get_hiera_model_base_plus
  backbone_class: swinv2_base_window16_256_timm_xview
  backbone:
    in_chans: 3
    input_dim: 2
    drop_path_rate: 0.2
    pretrained:  ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_base_patch4_window16_256.pth
    channel_last: True
    img_size: 512
  tiling: 'naive'
  xl_context:
    enabled: off
    skip_connection: off
    grad_ratio: 0.25
    tiling: naive_two_stream
    n_layer: 12
optimizer:
  name: adam
  base_lr: 1e-3
  min_lr_ratio: 0.01
  classifier_ratio: 1.0
  warmup_epochs: 0
  weight_decay: 1e-4
  momentum: 0.9
  nesterov: True
  scheduler: cosine
  mode: step
train:
  epochs: 480
  batch_size: 8
  val_batch_size: 2
  freeze_epochs: 0
  freeze_bn: false
  test_every: 40 
  test_reset: True
losses:
  losses:
    - name: mask_vessel
      type: Combo
      params: 
        field: vessel_mask 
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 1.0 
      display: True
    - name: mask_fishing 
      type: Combo
      params: 
        field: fishing_mask
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 2.0 
      display: True
    - name: center 
      type: Center
      params: 
      weight: 3e-7
      display: True
    - name: length
      type: Length
      params: 
      weight: 2.0
      display: True
eval_sampler: False
