base_configs: 
  - config/revswin_xl/4096_chip1024_lr1e-3.yaml
name: revswinv2_xl_4096_chip1024_lr1e-3_head3x
optimizer:
  base_lr: 1e-3
  classifier_ratio: 3.0
  warmup_epochs: 0
train:
  batch_size: 6