base_configs:
- config/cluster_paths.yaml
distributed: true
fsdp: false
fp16: true
name: xview_nonxl_backbone-swinv2-small_img-size-1024_bs-2_lr-3e-05
test: false
val: false
data:
  dataset: xview3
  fold: 77
  multiplier: 64
  num_workers: 8
  test: false
  crop_size: ${model.backbone.img_size}
  val_crop_size: ${model.backbone.img_size}
  batch_size: ${train.batch_size}
  val_batch_size: ${train.val_batch_size}
  overlap: 10
  positive_ratio: 0.85
  supercategories: null
  category_label_path: ''
model:
  name: EncoderDecoderV2
  patch_size: 16
  mlp_ratio: 4
  backbone_class: swinv2_small_window16_256_timm_xview
  backbone:
    in_chans: 3
    input_dim: 2
    drop_path_rate: 0.2
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_base_patch4_window16_256.pth
    channel_last: true
    img_size: 1024
  tiling: naive
  xl_context:
    enabled: false
    skip_connection: false
    grad_ratio: 0.25
    tiling: naive_two_stream
    n_layer: 12
optimizer:
  name: adam
  base_lr: 0.001
  min_lr_ratio: 0.01
  classifier_ratio: 1.0
  warmup_epochs: 0
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: true
  scheduler: cosine
  mode: step
  lr: 3.0e-05
train:
  epochs: 480
  batch_size: 4
  val_batch_size: 2
  freeze_epochs: 0
  freeze_bn: false
  test_every: 40
  test_reset: true
losses:
  losses:
  - name: mask_vessel
    type: Combo
    params:
      field: vessel_mask
      weights:
        bce: 1
        focal: 3
        dice: 1
    weight: 1.0
    display: true
  - name: mask_fishing
    type: Combo
    params:
      field: fishing_mask
      weights:
        bce: 1
        focal: 3
        dice: 1
    weight: 2.0
    display: true
  - name: center
    type: Center
    params: null
    weight: 3.0e-07
    display: true
  - name: length
    type: Length
    params: null
    weight: 2.0
    display: true
eval_sampler: false
