distributed: True
fsdp: False
fp16: True
name: revswinv2_chip512_swinpt_lr1e-3
output_dir: ${oc.env:OUTPUT_DIR, "/shared/jacklishufan/large-image-models/new"} 
test: False
val: False
data:
  dataset: xview3
  dir: ${oc.env:XVIEW3_ROOT, "/shared/group/xview3"} 
  shoreline_dir: ${oc.env:XVIEW3_ROOT, "/shared/group/xview3"} /shoreline/validation
  folds_csv:  ${oc.env:XVIEW3_FOLD_PATH, "meta/folds.csv"} 
  fold: 77
  multiplier: 64
  num_workers: 8
  test: False
  crop_size: 512
  val_crop_size: 512
  overlap: 10 
  positive_ratio: 0.85
  transforms:
    names:
      - None
    max_size: 2048
    height: 2048
    width: 2048
model: 
  name: TimmUnet
  backbone_class: revswinv2_tiny_window16_256_xview
  backbone:
    in_chans: 3
    input_dim: 2
    drop_path_rate: 0.2
    pretrained:  ckpts/swinv2_tiny_window16_256.pth
    channel_last: True
    img_size: 512
  resume: ''
  tiling: 'naive'
  xl_context:
    enabled: False
optimizer:
  name: sgd 
  base_lr: 1e-3
  min_lr_ratio: 0.01
  classifier_ratio: 1.0
  warmup_epochs: 0
  weight_decay: 1e-4
  momentum: 0.9
  nesterov: True
  scheduler: cosine
  mode: step
train:
  epochs: 120
  batch_size: 8
  val_batch_size: 2
  freeze_epochs: 0
  test_every: 20 
  test_reset: True
losses:
  losses:
    - name: mask_vessel
      type: Combo
      params: 
        field: vessel_mask 
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 1.0 
      display: True
    - name: mask_fishing 
      type: Combo
      params: 
        field: fishing_mask
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 2.0 
      display: True
    - name: center 
      type: Center
      params: 
      weight: 3e-7
      display: True
    - name: length
      type: Length
      params: 
      weight: 2.0
      display: True
