# @package _global_

# Specify default config order (least to highest)
defaults:
  - _self_
  - data: xview3
  - model: TimmUnet
    - encoder: revswinv2
  - optimizer: sgd
  - train: lr1e-3
  - losses: all_losses

distributed: True
fsdp: False
fp16: True
log_dir: logs
name: ''
test_reset: False
data:
  dataset: xview3
  dir: ''
  shoreline_dir: ''
  fold: 0
  folds_csv: ''
  multiplier: 64
  num_workers: 8
  test: False
  crop_size: 1024
  val_crop_size: 1024
  overlap: 10 
model: 
  name: TimmUnet
  encoder:
    name: revswinv2_large_window16_256_xview
    in_chans: 2
    drop_path_rate: 0.2
    pretrained: False
    channel_last: True
    patch_size: 16
    input_size: 256
  resume: ''
  tiling: 'naive'
optimizer:
  name: sgd 
  momentum: 0.9
  scheduler: 
    name: cosine
    mode: step
train:
  epochs: 120
  batch_size: 6
  base_lr: 1e-3
  min_lr_multiplier: 0.01
  warmup_lr_multiplier: 0.001
  classifier_multiplier: 1.0
  warmup_epochs: 0
  weight_decay: 1e-4
  val_batch_size: 2
  freeze_epochs: 0
  positive_ratio: 0.85
losses:
  - name: msk_v
    type: ComboLossCalculator
    weight: 1.0
    display: True
    params:
      field: vessel_mask
      weights:
        bce: 1
        focal: 3
        dice: 1
  - name: msk_f
    type: ComboLossCalculator
    weight: 2.0
    display: True
    params:
      field: fishing_mask
      weights:
        bce: 1
        focal: 3
        dice: 1
  - name: center
    type: CenterLossCalculator
    weight: 3e-7
    display: True
    params: 
  - name: length
    type: LengthLoss
    weight: 2
    display: True
    params: