output_dir: /p/app/projects/nga-frontier/gigaformer-runs/logs/%j
data:
  dir: /p/app/projects/nga-frontier/inaturalist2018
  shoreline_dir: /p/app/projects/nga-frontier/xview3/shoreline/validation
  folds_csv: /p/home/ritwik/dev/revswin-xl/meta/folds.csv
  category_label_path: /p/app/projects/nga-frontier/inaturalist2018/category-maps/category_label_reptilia_map.json
model:
  resume: /p/app/projects/nga-frontier/gigaformer-runs/logs/%j/resume/