output_dir: /home/ritwik/logs/%j
data:
  dir: /shared/ritwik/data/inaturalist2018
  shoreline_dir: /p/app/projects/nga-frontier/xview3/shoreline/validation
  folds_csv: /p/home/ritwik/dev/xview3-detection/meta/folds.csv
  category_label_path: /shared/ritwik/dev/xview3-detection/meta/category_label_reptilia_map.json
model:
  resume: /home/ritwik/logs/%j/resume/