losses:
  losses:
    - name: mask_vessel
      type: Combo
      params: 
        field: vessel_mask 
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 1.0 
      display: True
    - name: mask_fishing 
      type: Combo
      params: 
        field: fishing_mask
        weights: 
          bce: 1
          focal: 3
          dice: 1
      weight: 0.0 
      display: True
    - name: center 
      type: Center
      params: 
      weight: 3e-7
      display: True
    - name: length
      type: Length
      params: 
      weight: 0.0
      display: True