crop_size: 3072
data:
  positive_ratio: 0.85
  crop_size_val: 3072
  overlap_val: 10
# encoder_crop_size: 512
encoder_params:
  channels_last: true
  context_mode: none
  drop_path_rate: 0.2
  encoder: vit_base_patch16
  expected_stride: 16
  in_chans: 2
  out_indices: -2
  decoder_embed_dim: 12
  pretrained: /shared/jacklishufan/mae/mae_visualize_vit_base.pth
  ### specifica data
  drop_path: 0.1
  mlp_ratio: 4
  roll: off
  drop_rate: .1
  window_size: [1, 1, 2 ,2]
  transformer_xl:
    ext_len: 0
    no_memory: false
  block_extr_args:
    rel_pos_bias: abs
    grid: [2,2,4,4]
  inner_bias_mode: earth
  use_checkpoint: on
  decoder_conv_layers: 0
  patch_size: [1,1,8,8]
  block_extr_args_swin:
      hier_depths: [3,2, 6,] #[2, 2, 18, 2]
      decode_depths:  [3,4, 12] #[2, 2, 18, 2]
      num_heads: [8,8, 16] #[4, 8, 16, 32]
      down_sample_size: [2,16,6]
      embed_dim: [256,384,768] #[192,384,768,1536]
      norm_mode: [post, post,post]
      conv_depth_cat: 0
      skip: true
      inner_block: [WindowedAttentionBlock,WindowedAttentionBlock,GraphAttentionBlock] # ViTBlock,WindowedAttentionBlock,GraphAttentionBlock
losses:
- display: true
  name: msk_v
  params:
    field: vessel_mask
    weights:
      bce: 1
      dice: 1
      focal: 3
  type: ComboLossCalculator
  weight: 1.0
- display: true
  name: msk_f
  params:
    field: fishing_mask
    weights:
      bce: 1
      dice: 1
      focal: 3
  type: ComboLossCalculator
  weight: 2.0
- display: true
  name: center
  params: {}
  type: CenterLossCalculator
  weight: 3.0e-7
- display: true
  name: length
  params: {}
  type: LengthLoss
  weight: 0.1
multiplier: 64
network: HierVitND
optimizer:
  learning_rate: 5.0e-4
  momentum: 0.9
  nesterov: true
  schedule:
    epochs: 800
    mode: step
    params:
      eta_min: 4.0e-06
    type: cosine
    warmup_epoches: 40
  train_bs: 2
  type: AdamW
  val_bs: 1
  weight_decay: 0.0001
tiling: naive
