base_configs: 
  - config/base.yaml
name: revswinv2_xl_4096_chip512_swinpt_lr1e-3_inaturalist
data:
  dataset: inaturalist
  dir: /shared/ritwik/data/inaturalist2018
  crop_size: 2048
  val_crop_size: 2048
  num_workers: 1
  transforms:
    names:
      - SmallestMaxSize
      - RandomCrop
      - Normalize
    mean: [0.,0.,0.]
    std: [1.,1.,1.]
    max_size: 2048
    height: 2048
    width: 2048
  transforms_val: 
    names:
      - SmallestMaxSize
      - RandomCrop
      - Normalize
    mean: [0.,0.,0.]
    std: [1.,1.,1.]
    max_size: 2048
    height: 2048
    width: 2048
model: 
  name: EncoderDecoderV2
  num_classes: 9999 # Monkey 
  mlp_ratio: 4
  backbone:
    img_size: 512
    input_dim: 3
    use_vanilla_backward: True
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_tiny_window16_256.pth
  xl_context:
    enabled: true
    n_layer: 12
  resume: ''
optimizer:
  base_lr: 1e-3
  classifier_ratio: 1.0
  warmup_epochs: 0
train:
  epochs: 20
  batch_size: 1
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 1
  test_reset: True
val: False
losses:
  losses:
    - name: cls
      type: CrossEntrophy
      params: 
        field: label 
      weight: 1.0
      display: on