base_configs: 
  - config/base.yaml
name: revswinv2_xl_4096_chip512_swinpt_lr1e-3_head3x
data:
  crop_size: 4096
  val_crop_size: 4096
model: 
  backbone:
    img_size: 512
    pretrained: ckpts/swinv2_tiny_window16_256.pth
  xl_context:
    enabled: True
    no_memory: False
    n_layer: 12
optimizer:
  base_lr: 1e-3
  classifier_ratio: 3.0
  warmup_epochs: 0
train:
  epochs: 20
  batch_size: 1
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 1
  test_reset: True