base_configs: 
  - config/revswin_xl/4096_chip512_lr1e-3_inaturalist.yaml
  - config/base.yaml
  # - config/cluster_paths.yaml
name: revswinv2_xl_4096_chip512_swinpt_lr1e-3_inaturalist
data:
  crop_size: 2048
  val_crop_size: 2048
  transforms:

    max_size: 2048
    crop_size: 2048
model: 
  name: EncoderDecoderV2
  task: classification
  backbone:
    img_size: 512
    input_dim: 3
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_tiny_window16_256.pth
  xl_context:
    enabled: true
    n_layer: 12
  resume: ''
optimizer:
  base_lr: 1e-3
  classifier_ratio: 1.0
  warmup_epochs: 0
train:
  epochs: 20
  batch_size: 1
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 1
  test_reset: True
val: False
