base_configs: 
  - config/base.yaml
  - config/cluster_paths.yaml
name: revswinv2_xl_4096_chip512_swinpt_lr3e-3
data:
  crop_size: 4096
  val_crop_size: 4096
  num_workers: 1
model: 
  backbone:
    img_size: 512
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_tiny_window16_256.pth
  xl_context:
    enabled: True
    no_memory: False
    n_layer: 12
  resume: ''
optimizer:
  base_lr: 3e-3
  classifier_ratio: 1.0
  warmup_epochs: 0
train:
  epochs: 20
  batch_size: 24
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 1
  test_reset: True
val: False