base_configs: 
  - config/base.yaml
  - config/cluster_paths.yaml
name: revswinv2_xl_8192_chip1024_lr1e-3
data:
  crop_size: 8192
  val_crop_size: 8192
  num_workers: 1
model: 
  backbone:
    img_size: 1024
    pretrained: ${oc.env:PRETRAINED_CKPT_PATH, "./ckpts"}/swinv2_tiny_window16_256.pth
  xl_context:
    enabled: True
    no_memory: False
    n_layer: 12
  resume: ''
optimizer:
  base_lr: 1e-3
  classifier_ratio: 1.0
  warmup_epochs: 0
train:
  epochs: 20
  batch_size: 4 
  val_batch_size: 1
  freeze_epochs: 0
  test_every: 2
  test_reset: True
val: False